In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
import joblib

In [3]:
df = pd.read_csv("TrainDataset2025.csv")

pd.set_option('display.max_columns', None)
df.head()

,ID,pCR (outcome),RelapseFreeSurvival (outcome),Age,ER,PgR,HER2,TrippleNegative,ChemoGrade,Proliferation,HistologyType,LNStatus,TumourStage,Gene,original_shape_Elongation,original_shape_Flatness,original_shape_LeastAxisLength,original_shape_MajorAxisLength,original_shape_Maximum2DDiameterColumn,original_shape_Maximum2DDiameterRow,original_shape_Maximum2DDiameterSlice,original_shape_Maximum3DDiameter,original_shape_MeshVolume,original_shape_MinorAxisLength,original_shape_Sphericity,original_shape_SurfaceArea,original_shape_SurfaceVolumeRatio,original_shape_VoxelVolume,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,original_firstorder_Minimum,original_firstorder_Range,original_firstorder_RobustMeanAbsoluteDeviation,original_firstorder_RootMeanSquared,original_firstorder_Skewness,original_firstorder_TotalEnergy,original_firstorder_Uniformity,original_firstorder_Variance,original_glcm_Autocorrelation,original_glcm_ClusterProminence,original_glcm_ClusterShade,original_glcm_ClusterTendency,original_glcm_Contrast,original_glcm_Correlation,original_glcm_DifferenceAverage,original_glcm_DifferenceEntropy,original_glcm_DifferenceVariance,original_glcm_Id,original_glcm_Idm,original_glcm_Idmn,original_glcm_Idn,original_glcm_Imc1,original_glcm_Imc2,original_glcm_InverseVariance,original_glcm_JointAverage,original_glcm_JointEnergy,original_glcm_JointEntropy,original_glcm_MCC,original_glcm_MaximumProbability,original_glcm_SumAverage,original_glcm_SumEntropy,original_glcm_SumSquares,original_gldm_DependenceEntropy,original_gldm_DependenceNonUniformity,original_gldm_DependenceNonUniformityNormalized,original_gldm_DependenceVariance,original_gldm_GrayLevelNonUniformity,original_gldm_GrayLevelVariance,original_gldm_HighGrayLevelEmphasis,original_gldm_LargeDependenceEmphasis,original_gldm_LargeDependenceHighGrayLevelEmphasis,original_gldm_LargeDependenceLowGrayLevelEmphasis,original_gldm_LowGrayLevelEmphasis,original_gldm_SmallDependenceEmphasis,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,original_glrlm_GrayLevelNonUniformity,original_glrlm_GrayLevelNonUniformityNormalized,original_glrlm_GrayLevelVariance,original_glrlm_HighGrayLevelRunEmphasis,original_glrlm_LongRunEmphasis,original_glrlm_LongRunHighGrayLevelEmphasis,original_glrlm_LongRunLowGrayLevelEmphasis,original_glrlm_LowGrayLevelRunEmphasis,original_glrlm_RunEntropy,original_glrlm_RunLengthNonUniformity,original_glrlm_RunLengthNonUniformityNormalized,original_glrlm_RunPercentage,original_glrlm_RunVariance,original_glrlm_ShortRunEmphasis,original_glrlm_ShortRunHighGrayLevelEmphasis,original_glrlm_ShortRunLowGrayLevelEmphasis,original_glszm_GrayLevelNonUniformity,original_glszm_GrayLevelNonUniformityNormalized,original_glszm_GrayLevelVariance,original_glszm_HighGrayLevelZoneEmphasis,original_glszm_LargeAreaEmphasis,original_glszm_LargeAreaHighGrayLevelEmphasis,original_glszm_LargeAreaLowGrayLevelEmphasis,original_glszm_LowGrayLevelZoneEmphasis,original_glszm_SizeZoneNonUniformity,original_glszm_SizeZoneNonUniformityNormalized,original_glszm_SmallAreaEmphasis,original_glszm_SmallAreaHighGrayLevelEmphasis,original_glszm_SmallAreaLowGrayLevelEmphasis,original_glszm_ZoneEntropy,original_glszm_ZonePercentage,original_glszm_ZoneVariance,original_ngtdm_Busyness,original_ngtdm_Coarseness,original_ngtdm_Complexity,original_ngtdm_Contrast,original_ngtdm_Strength
0,TRG002174,1,144.0,41.0,0,0,0,1,3,3,1,1,2,1,0.813912,0.724080,23.781937,32.844370,37.696154,38.626416,34.713110,39.572718,14209.458330,26.732440,0.771675,3676.500012,0.258736,14263,-0.163500,0.708860,2897.68930,0.738088,0.406537,4.594629,2.114799,0.278008,0.248168,0.217628,-1.251833,3.366632,0.174026,0.450734,0.386237,2897.68930,0.670258,0.141574,3.328814,0.725849,-0.425324,0.438760,0.184265,0.407895,0.184265,0.685680,0.149585,0.907867,0.907867,0.963147,0.938578,-0.149786,0.425720,0.184265,1.806982,0.538903,1.309203,0.407895,0.714849,3.613964,1.124938,0.155756,4.529461,1164.363949,0.081635,38.233794,9559.892659,0.164871,3.375307,456.983173,1714.810208,142.526414,0.406173,0.005563,0.011679,0.004033,1805.333660,0.503341,0.248329,2.619511,36.191087,137.835476,10.779989,0.595122,3.865811,677.118614,0.184874,0.251409,19.138811,0.409396,0.789987,0.314248,27.545455,0.834711,0.082645,1.272727,4067578.818,1.565522e+07,1.170667e+06,0.931818,5.969697,0.180900,0.403535,0.517172,0.375126,3.325332,0.002314,3880771.500,473.464852,0.000768,0.182615,0.030508,0.000758
1,TRG002178,0,142.0,39.0,1,1,0,0,3,3,1,1,2,0,0.666118,0.476173,20.715461,43.504095,51.971146,41.761226,36.400549,53.310412,14202.708330,28.978871,0.603481,4699.678466,0.330900,14254,0.665558,2.322627,41105.32510,0.179893,0.730463,3.884960,3.857952,0.499454,1.562901,1.632745,-1.106491,4.964442,0.318599,1.698168,-0.634246,41105.32510,0.947174,0.441115,3.934749,0.070286,-0.048574,0.039166,0.027998,0.157776,0.027998,0.183795,0.027197,0.986001,0.986001,0.994400,0.990667,-0.070082,0.105206,0.027998,1.982916,0.939221,0.240095,0.157776,0.968917,3.965832,0.212098,0.016791,2.799725,4650.251438,0.326242,29.160771,13501.014310,0.026413,3.918549,585.940648,2342.457065,146.811544,0.270363,0.006518,0.012337,0.005064,1302.579572,0.694474,0.152763,3.433408,109.743182,438.113168,27.650685,0.391648,4.255471,159.837285,0.084497,0.130916,44.699577,0.241148,0.442279,0.190865,78.025000,0.975313,0.012344,1.037500,2403756.075,9.614769e+06,6.010027e+05,0.990625,15.850000,0.198125,0.444391,0.444391,0.444391,3.032144,0.005612,2372009.744,59.459710,0.004383,0.032012,0.001006,0.003685
2,TRG002204,1,135.0,31.0,0,0,0,1,2,1,1,0,2,1,0.645083,0.594470,21.659822,36.435505,32.984845,40.447497,42.379240,44.384682,10858.375000,23.503921,0.608183,3899.055524,0.359083,10960,0.638035,1.961740,19774.94893,0.136183,0.509910,4.760064,3.841710,0.400199,1.219685,1.153095,-1.025610,4.867321,0.231278,1.343236,0.545105,19774.94893,0.962589,0.316651,3.955045,0.043376,-0.031359,0.026057,0.020003,0.131035,0.020003,0.141291,0.019599,0.989998,0.989998,0.995999,0.993332,-0.048997,0.086544,0.020003,1.988349,0.957372,0.178540,0.131035,0.978347,3.976698,0.158537,0.011515,2.863091,3374.309307,0.307875,27.615779,10549.970990,0.018706,3.942792,584.343248,2336.739325,146.244229,0.264302,0.007181,0.013216,0.005672,1102.109263,0.764847,0.117576,3.590626,100.817995,402.737100,25.338218,0.352343,4.232295,114.255050,0.079355,0.130959,38.588656,0.222151,0.503046,0.151927,72.027027,0.973338,0.013331,1.040541,1561963.432,6.247801e+06,3.905040e+05,0.989865,20.405405,0.275749,0.534549,0.534549,0.534549,2.485848,0.006752,1540027.421,33.935384,0.007584,0.024062,0.000529,0.006447
3,TRG002206,0,12.0,35.0,0,0,0,1,3,3,1,1,3,1,0.770842,0.501228,26.590504,53.050724,66.910388,44.944410,66.760767,69.000000,26748.208330,40.893735,0.474509,9115.275207,0.340781,26899,0.759496,2.164869,72854.17151,0.087137,0.740609,3.421056,3.030400,0.442713,1.549668,1.660720,-0.851106,3.881506,0.309734,1.645732,-0.792678,72854.17151,0.978307,0.306963,3.973627,0.025128,-0.018371,0.015236,0.011845,0.122613,0.011845,0.092635,0.011702,0.994078,0.994078,0.997631,0.996052,-0.056651,0.065831,0.011845,1.993183,0.974758,0.114284,0.122613,0.987261,3.986367,0.102439,0.006770,2.756432,8662.085096,0.322023,22.976388,26315.470500,0.010847,3.967099,594.497230,2377.642849,148.710826,0.258225,0.004902,0.010811,0.003424,2701.187578,0.841781,0.079110,3.739820,125.498739,501.648278,31.461354,0.315045,4.412648,212.625994,0.065202,0.118981,48.370607,0.161327,0.399896,0.101685,99.019802,0.980394,0.009803,1.029703,7007670.723,2.803063e+07,1.751932e+06,0.992574,25.554455,0.253014,0.506185,0.506185,0.506185,2.606255,0.003755,6936740.794,46.859265,0.005424,0.013707,0.000178,0.004543
4,TRG002210,0,109.0,61.0,1,0,0,0,2,1,1,0,2,1,0.861035,0.750267,20.456571,27.265716,33.241540,30.594117,31.384710,35.042831,8846.541667,23.476732,0.756228,2735.354881,0.309200,8894,0.434385,1.832410,15697.30914,0.183666,0.787978,3.107181,2.315364,0.447799,1.209800,1.311328,-0.866201,3.181566,0.324996,1.328508,-0.732889,15697.30914,0.945787,0.301317,3.933264,0.069301,-0.048455,0.039564,0.028921,0.155224,0.028921,0.188503,0.028068,0.985540,0.985540,0.994216,0.990360,-0.061986,0.106835,0.028921,1.982575,0.937690,0.245543,0.155224,0.968114,3.965150,0.216623,0.017121,2.676170,3195.159883,0.359249,29.518487,8411.830447,0.027106,3.916348,594.187317,2375.516078,148.855127,0.270913,0.007222,0.012956,0.005788,750.787780,0.674880,0.162560,3.385162,110.775276,442.211336,27.916261,0.403709,4.140589,101.119011,0.091210,0.124509,41.234090,0.261101,0.473278,0.208056,56.034483,0.966112,0.016944,1.051724,1288913.690,5.155465e+06,3.222760e+05,0.987069,12.551724,0.216409,0.462282,0.462282,0.462282,2.809279,0.006521,1265399.054,39.621023,0.006585,0.034148,0.001083,0.005626

In [4]:
df = df.replace(999, np.nan)
df.isna().sum().head()

ID                               0
pCR (outcome)                    5
RelapseFreeSurvival (outcome)    0
Age                              0
ER                               0
dtype: int64

In [5]:
ID_COL = "ID"
TARGET_COL = "RelapseFreeSurvival (outcome)"

patient_ids = df[ID_COL]
y = df[TARGET_COL]

# remove ID and target, and also pCR
X = df.drop(columns=[ID_COL, TARGET_COL, "pCR (outcome)"])

X.shape

(400, 118)

In [6]:
scaler_iter = StandardScaler()
X_scaled = scaler_iter.fit_transform(X)

joblib.dump(scaler_iter, "scaler_iter.pkl")
print("Saved: scaler_iter.pkl")

Saved: scaler_iter.pkl

In [7]:
iter_imputer = IterativeImputer(max_iter=20, random_state=42)
X_iter = iter_imputer.fit_transform(X_scaled)

print("Remaining NaN after imputation:", np.isnan(X_iter).sum())

joblib.dump(iter_imputer, "iter_imputer.pkl")
print("Saved: iter_imputer.pkl")

Remaining NaN after imputation: 0
Saved: iter_imputer.pkl

In [8]:
X_iter_df = pd.DataFrame(X_iter, columns=X.columns)

Q1 = X_iter_df.quantile(0.25)
Q3 = X_iter_df.quantile(0.75)
IQR = Q3 - Q1

X_clipped = X_iter_df.clip(
    lower=Q1 - 1.5 * IQR,
    upper=Q3 + 1.5 * IQR,
    axis=1
)

X_clipped.head()

,Age,ER,PgR,HER2,TrippleNegative,ChemoGrade,Proliferation,HistologyType,LNStatus,TumourStage,Gene,original_shape_Elongation,original_shape_Flatness,original_shape_LeastAxisLength,original_shape_MajorAxisLength,original_shape_Maximum2DDiameterColumn,original_shape_Maximum2DDiameterRow,original_shape_Maximum2DDiameterSlice,original_shape_Maximum3DDiameter,original_shape_MeshVolume,original_shape_MinorAxisLength,original_shape_Sphericity,original_shape_SurfaceArea,original_shape_SurfaceVolumeRatio,original_shape_VoxelVolume,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,original_firstorder_Minimum,original_firstorder_Range,original_firstorder_RobustMeanAbsoluteDeviation,original_firstorder_RootMeanSquared,original_firstorder_Skewness,original_firstorder_TotalEnergy,original_firstorder_Uniformity,original_firstorder_Variance,original_glcm_Autocorrelation,original_glcm_ClusterProminence,original_glcm_ClusterShade,original_glcm_ClusterTendency,original_glcm_Contrast,original_glcm_Correlation,original_glcm_DifferenceAverage,original_glcm_DifferenceEntropy,original_glcm_DifferenceVariance,original_glcm_Id,original_glcm_Idm,original_glcm_Idmn,original_glcm_Idn,original_glcm_Imc1,original_glcm_Imc2,original_glcm_InverseVariance,original_glcm_JointAverage,original_glcm_JointEnergy,original_glcm_JointEntropy,original_glcm_MCC,original_glcm_MaximumProbability,original_glcm_SumAverage,original_glcm_SumEntropy,original_glcm_SumSquares,original_gldm_DependenceEntropy,original_gldm_DependenceNonUniformity,original_gldm_DependenceNonUniformityNormalized,original_gldm_DependenceVariance,original_gldm_GrayLevelNonUniformity,original_gldm_GrayLevelVariance,original_gldm_HighGrayLevelEmphasis,original_gldm_LargeDependenceEmphasis,original_gldm_LargeDependenceHighGrayLevelEmphasis,original_gldm_LargeDependenceLowGrayLevelEmphasis,original_gldm_LowGrayLevelEmphasis,original_gldm_SmallDependenceEmphasis,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,original_glrlm_GrayLevelNonUniformity,original_glrlm_GrayLevelNonUniformityNormalized,original_glrlm_GrayLevelVariance,original_glrlm_HighGrayLevelRunEmphasis,original_glrlm_LongRunEmphasis,original_glrlm_LongRunHighGrayLevelEmphasis,original_glrlm_LongRunLowGrayLevelEmphasis,original_glrlm_LowGrayLevelRunEmphasis,original_glrlm_RunEntropy,original_glrlm_RunLengthNonUniformity,original_glrlm_RunLengthNonUniformityNormalized,original_glrlm_RunPercentage,original_glrlm_RunVariance,original_glrlm_ShortRunEmphasis,original_glrlm_ShortRunHighGrayLevelEmphasis,original_glrlm_ShortRunLowGrayLevelEmphasis,original_glszm_GrayLevelNonUniformity,original_glszm_GrayLevelNonUniformityNormalized,original_glszm_GrayLevelVariance,original_glszm_HighGrayLevelZoneEmphasis,original_glszm_LargeAreaEmphasis,original_glszm_LargeAreaHighGrayLevelEmphasis,original_glszm_LargeAreaLowGrayLevelEmphasis,original_glszm_LowGrayLevelZoneEmphasis,original_glszm_SizeZoneNonUniformity,original_glszm_SizeZoneNonUniformityNormalized,original_glszm_SmallAreaEmphasis,original_glszm_SmallAreaHighGrayLevelEmphasis,original_glszm_SmallAreaLowGrayLevelEmphasis,original_glszm_ZoneEntropy,original_glszm_ZonePercentage,original_glszm_ZoneVariance,original_ngtdm_Busyness,original_ngtdm_Coarseness,original_ngtdm_Complexity,original_ngtdm_Contrast,original_ngtdm_Strength
0,-0.988097,-1.099975,-0.826767,-0.655826,1.414214,1.198570,1.860978,-0.417799,0.934473,-0.677748,1.273518,0.592892,1.028945,0.071441,-0.478742,-0.426401,-0.235863,-0.468358,-0.524498,-0.175535,-0.308443,1.036049,-0.259476,-1.087764,-0.176780,-1.026310,-2.287226,-0.410884,1.962060,-1.896993,1.612398,-1.364938,-1.937554,-2.365918,-2.332661,-0.402844,-1.165653,-1.942412,-2.398728,1.315601,-0.410884,-2.160535,-1.265387,-0.622981,1.799379,-1.784718,2.048198,2.653858,0.418830,2.653858,2.312730,2.658016,-2.653858,-2.653858,-2.653858,-2.653858,-0.089944,1.250498,2.653858,-0.499062,-2.604810,2.438091,0.418233,-2.293219,-0.499062,2.356563,2.387825,2.336564,-0.437096,-1.707859,0.544383,-0.268511,2.160535,-0.592922,-1.664880,-1.010271,-0.178247,0.592922,0.029990,0.066315,0.015711,-0.084533,-1.117937,1.117937,-0.908498,-0.907049,-0.874661,-0.711569,0.908498,-0.221205,0.709184,1.487889,1.575373,-0.628974,1.253934,1.769572,0.892663,-0.304063,-0.324297,0.324297,0.031639,-0.095273,-0.089699,-0.072977,-0.031639,-0.326868,-0.439871,0.071207,0.729513,-0.098979,0.789528,-0.427579,-0.075005,0.179069,-0.183281,2.667250,1.610433,-0.246730
1,-1.170999,0.909112,1.209530,-0.655826,-0.707107,1.198570,1.860978,-0.417799,0.934473,-0.677748,-0.785226,-0.309105,-0.434837,-0.237188,-0.121351,0.165771,-0.113947,-0.406647,-0.084778,-0.175734,-0.157788,0.026216,-0.181422,-0.508733,-0.177044,0.632565,-0.320962,-0.194897,-0.545429,-1.147022,1.354199,-0.096316,-0.901751,0.148116,0.210393,-0.115698,-0.051450,-1.098646,-0.076746,-0.968924,-0.194897,0.607558,-0.666715,0.399087,-0.730053,0.669429,-0.648992,-0.562475,-0.847362,-0.562475,-0.478603,-0.557788,0.562475,0.562475,0.562475,0.562475,0.683457,-0.768358,-0.562475,0.377255,0.632012,-0.608291,-0.846769,0.612171,0.377255,-0.611193,-0.646442,-0.969332,-0.109295,0.868828,-0.450219,-0.149067,-0.607558,0.399890,0.861963,0.701404,-0.122068,-0.399890,0.467825,0.289228,0.507105,-0.205283,-0.000743,0.000743,0.386308,0.602007,0.644191,0.286135,-0.386308,0.738996,-0.381065,-0.821002,-0.828662,0.496965,-0.353144,-0.765192,-0.172410,0.420447,0.814986,-0.814986,-0.575949,-0.096862,-0.091605,-0.073752,0.575949,0.359933,-0.309800,0.324132,0.292187,0.330194,0.405739,0.937740,-0.077144,-0.113827,-0.183281,-0.528922,-0.592650,-0.221445
2,-1.902606,-1.099975,-0.826767,-0.655826,1.414214,-0.800726,-0.751612,-0.417799,-1.070122,-0.677748,1.273518,-0.437485,0.263658,-0.142142,-0.358341,-0.621841,-0.165039,-0.187999,-0.370476,-0.274125,-0.524960,0.054451,-0.242498,-0.282601,-0.273716,0.577493,-0.822409,-0.315477,-0.741780,-1.657658,1.612398,-0.108136,-1.366012,-0.540990,-0.768648,0.044093,-0.119176,-1.608272,-0.816656,1.671253,-0.315477,0.761648,-0.915472,0.436114,-0.833884,0.781570,-0.745242,-0.738944,-0.982734,-0.738944,-0.714995,-0.757451,0.738944,0.738944,0.738944,0.738944,0.888055,-0.885909,-0.738944,0.407102,0.778770,-0.783690,-0.982014,0.736141,0.407102,-0.785327,-0.766244,-0.848226,-0.229280,0.675351,-0.619584,-0.238504,-0.761648,0.444195,0.830663,0.685811,-0.129505,-0.444195,0.771252,0.587436,0.797115,-0.253432,0.410598,-0.410598,0.636422,0.418891,0.465254,0.149380,-0.636422,0.681886,-0.477137,-0.939265,-0.827810,0.227782,-0.534603,-0.322210,-0.508533,0.334361,0.798989,-0.798989,-0.568095,-0.097666,-0.092667,-0.074039,0.568095,0.676589,0.276355,0.882281,0.833929,0.888831,-0.309375,1.409308,-0.078323,-0.138272,-0.183281,-0.697655,-0.649565,-0.197586
3,-1.536803,-1.099975,-0.826767,-0.655826,1.414214,1.198570,1.860978,-0.417799,0.934473,0.437887,1.273518,0.330031,-0.286897,0.354112,0.198721,0.785498,0.009849,0.703661,0.417418,0.193360,0.641270,-0.748127,0.155426,-0.429453,0.194057,0.820527,-0.540164,-0.015421,-0.962099,-1.123530,0.769419,-0.698587,-1.167155,0.121547,0.267493,0.388853,-0.806615,-1.150382,-0.186057,-1.323599,-0.015421,0.918768,-0.934835,0.470016,-0.904292,0.866173,-0.824690,-0.919033,-1.025371,-0.919033,-0.985606,-0.964938,0.919033,0.919033,0.919033,0.919033,0.813781,-1.016377,-0.919033,0.433661,0.919347,-0.966785,-1.024611,0.853320,0.433661,-0.967706,-0.873986,-1.052075,0.267965,0.824382,-1.128162,0.239304,-0.918768,0.488618,1.029624,0.797361,-0.097167,-0.488618,-0.272792,-0.228118,-0.274788,0.130630,0.860285,-0.860285,0.873770,0.925261,0.965562,0.511492,-0.873770,1.126312,-0.269805,-1.264815,-1.066791,0.658673,-1.115581,-1.074165,-0.942236,0.721776,0.856162,-0.856162,-0.596088,-0.092465,-0.085795,-0.072185,0.596088,1.034510,0.104683,0.706687,0.663496,0.713083,-0.151761,0.168875,-0.070674,-0.125894,-0.183281,-0.917409,-0.691620,-0.214034
4,0.840921,0.909112,-0.826767,-0.655826,-0.707107,-0.800726,-0.751612,-0.417799,-1.070122,-0.677748,1.273518,0.880483,1.183572,-0.263244,-0.665779,-0.611192,-0.548245,-0.590082,-0.669492,-0.333314,-0.526783,0.943305,-0.331273,-0.682848,-0.334348,0.170008,-1.002111,-0.338528,-0.528477,-1.013861,0.373760,-1.218972,-1.143366,-0.560838,-0.445669,0.359029,-1.294705,-1.061309,-0.847360,-1.189751,-0.338528,0.593697,-0.946119,0.396377,-0.733851,0.670209,-0.646068,-0.542092,-0.860282,-0.542092,-0.452418,-0.534920,0.542092,0.542092,0.542092,0.542092,0.762015,-0.758097,-0.542092,0.375380,0.619632,-0.592767,-0.859678,0.601616,0.375380,-0.596483,-0.638939,-1.205472,-0.246127,1.216525,-0.411005,-0.303305,-0.593697,0.395867,1.023552,0.791561,-0.095276,-0.395867,0.790007,0.499117,0.852575,-0.337811,-0.115270,0.115270,0.309556,0.623182,0.664921,0.301841,-0.309556,0.455904,-0.504823,-0.666583,-0.956489,0.344312,-0.162562,-0.539216,-0.024014,0.104828,0.740434,-0.740434,-0.539208,-0.097927,-0.093011,-0.074132,0.539208,0.130663,-0.171733,0.434892,0.399691,0.441051,0.114003,1.313876,-0.078713,-0.132826,-0.183281,-0.483605,-0.583366,-0.204678

In [9]:
df_clean_iter = pd.concat([patient_ids, X_clipped, y], axis=1)
df_clean_iter.head()

,ID,Age,ER,PgR,HER2,TrippleNegative,ChemoGrade,Proliferation,HistologyType,LNStatus,TumourStage,Gene,original_shape_Elongation,original_shape_Flatness,original_shape_LeastAxisLength,original_shape_MajorAxisLength,original_shape_Maximum2DDiameterColumn,original_shape_Maximum2DDiameterRow,original_shape_Maximum2DDiameterSlice,original_shape_Maximum3DDiameter,original_shape_MeshVolume,original_shape_MinorAxisLength,original_shape_Sphericity,original_shape_SurfaceArea,original_shape_SurfaceVolumeRatio,original_shape_VoxelVolume,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,original_firstorder_Minimum,original_firstorder_Range,original_firstorder_RobustMeanAbsoluteDeviation,original_firstorder_RootMeanSquared,original_firstorder_Skewness,original_firstorder_TotalEnergy,original_firstorder_Uniformity,original_firstorder_Variance,original_glcm_Autocorrelation,original_glcm_ClusterProminence,original_glcm_ClusterShade,original_glcm_ClusterTendency,original_glcm_Contrast,original_glcm_Correlation,original_glcm_DifferenceAverage,original_glcm_DifferenceEntropy,original_glcm_DifferenceVariance,original_glcm_Id,original_glcm_Idm,original_glcm_Idmn,original_glcm_Idn,original_glcm_Imc1,original_glcm_Imc2,original_glcm_InverseVariance,original_glcm_JointAverage,original_glcm_JointEnergy,original_glcm_JointEntropy,original_glcm_MCC,original_glcm_MaximumProbability,original_glcm_SumAverage,original_glcm_SumEntropy,original_glcm_SumSquares,original_gldm_DependenceEntropy,original_gldm_DependenceNonUniformity,original_gldm_DependenceNonUniformityNormalized,original_gldm_DependenceVariance,original_gldm_GrayLevelNonUniformity,original_gldm_GrayLevelVariance,original_gldm_HighGrayLevelEmphasis,original_gldm_LargeDependenceEmphasis,original_gldm_LargeDependenceHighGrayLevelEmphasis,original_gldm_LargeDependenceLowGrayLevelEmphasis,original_gldm_LowGrayLevelEmphasis,original_gldm_SmallDependenceEmphasis,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,original_glrlm_GrayLevelNonUniformity,original_glrlm_GrayLevelNonUniformityNormalized,original_glrlm_GrayLevelVariance,original_glrlm_HighGrayLevelRunEmphasis,original_glrlm_LongRunEmphasis,original_glrlm_LongRunHighGrayLevelEmphasis,original_glrlm_LongRunLowGrayLevelEmphasis,original_glrlm_LowGrayLevelRunEmphasis,original_glrlm_RunEntropy,original_glrlm_RunLengthNonUniformity,original_glrlm_RunLengthNonUniformityNormalized,original_glrlm_RunPercentage,original_glrlm_RunVariance,original_glrlm_ShortRunEmphasis,original_glrlm_ShortRunHighGrayLevelEmphasis,original_glrlm_ShortRunLowGrayLevelEmphasis,original_glszm_GrayLevelNonUniformity,original_glszm_GrayLevelNonUniformityNormalized,original_glszm_GrayLevelVariance,original_glszm_HighGrayLevelZoneEmphasis,original_glszm_LargeAreaEmphasis,original_glszm_LargeAreaHighGrayLevelEmphasis,original_glszm_LargeAreaLowGrayLevelEmphasis,original_glszm_LowGrayLevelZoneEmphasis,original_glszm_SizeZoneNonUniformity,original_glszm_SizeZoneNonUniformityNormalized,original_glszm_SmallAreaEmphasis,original_glszm_SmallAreaHighGrayLevelEmphasis,original_glszm_SmallAreaLowGrayLevelEmphasis,original_glszm_ZoneEntropy,original_glszm_ZonePercentage,original_glszm_ZoneVariance,original_ngtdm_Busyness,original_ngtdm_Coarseness,original_ngtdm_Complexity,original_ngtdm_Contrast,original_ngtdm_Strength,RelapseFreeSurvival (outcome)
0,TRG002174,-0.988097,-1.099975,-0.826767,-0.655826,1.414214,1.198570,1.860978,-0.417799,0.934473,-0.677748,1.273518,0.592892,1.028945,0.071441,-0.478742,-0.426401,-0.235863,-0.468358,-0.524498,-0.175535,-0.308443,1.036049,-0.259476,-1.087764,-0.176780,-1.026310,-2.287226,-0.410884,1.962060,-1.896993,1.612398,-1.364938,-1.937554,-2.365918,-2.332661,-0.402844,-1.165653,-1.942412,-2.398728,1.315601,-0.410884,-2.160535,-1.265387,-0.622981,1.799379,-1.784718,2.048198,2.653858,0.418830,2.653858,2.312730,2.658016,-2.653858,-2.653858,-2.653858,-2.653858,-0.089944,1.250498,2.653858,-0.499062,-2.604810,2.438091,0.418233,-2.293219,-0.499062,2.356563,2.387825,2.336564,-0.437096,-1.707859,0.544383,-0.268511,2.160535,-0.592922,-1.664880,-1.010271,-0.178247,0.592922,0.029990,0.066315,0.015711,-0.084533,-1.117937,1.117937,-0.908498,-0.907049,-0.874661,-0.711569,0.908498,-0.221205,0.709184,1.487889,1.575373,-0.628974,1.253934,1.769572,0.892663,-0.304063,-0.324297,0.324297,0.031639,-0.095273,-0.089699,-0.072977,-0.031639,-0.326868,-0.439871,0.071207,0.729513,-0.098979,0.789528,-0.427579,-0.075005,0.179069,-0.183281,2.667250,1.610433,-0.246730,144.0
1,TRG002178,-1.170999,0.909112,1.209530,-0.655826,-0.707107,1.198570,1.860978,-0.417799,0.934473,-0.677748,-0.785226,-0.309105,-0.434837,-0.237188,-0.121351,0.165771,-0.113947,-0.406647,-0.084778,-0.175734,-0.157788,0.026216,-0.181422,-0.508733,-0.177044,0.632565,-0.320962,-0.194897,-0.545429,-1.147022,1.354199,-0.096316,-0.901751,0.148116,0.210393,-0.115698,-0.051450,-1.098646,-0.076746,-0.968924,-0.194897,0.607558,-0.666715,0.399087,-0.730053,0.669429,-0.648992,-0.562475,-0.847362,-0.562475,-0.478603,-0.557788,0.562475,0.562475,0.562475,0.562475,0.683457,-0.768358,-0.562475,0.377255,0.632012,-0.608291,-0.846769,0.612171,0.377255,-0.611193,-0.646442,-0.969332,-0.109295,0.868828,-0.450219,-0.149067,-0.607558,0.399890,0.861963,0.701404,-0.122068,-0.399890,0.467825,0.289228,0.507105,-0.205283,-0.000743,0.000743,0.386308,0.602007,0.644191,0.286135,-0.386308,0.738996,-0.381065,-0.821002,-0.828662,0.496965,-0.353144,-0.765192,-0.172410,0.420447,0.814986,-0.814986,-0.575949,-0.096862,-0.091605,-0.073752,0.575949,0.359933,-0.309800,0.324132,0.292187,0.330194,0.405739,0.937740,-0.077144,-0.113827,-0.183281,-0.528922,-0.592650,-0.221445,142.0
2,TRG002204,-1.902606,-1.099975,-0.826767,-0.655826,1.414214,-0.800726,-0.751612,-0.417799,-1.070122,-0.677748,1.273518,-0.437485,0.263658,-0.142142,-0.358341,-0.621841,-0.165039,-0.187999,-0.370476,-0.274125,-0.524960,0.054451,-0.242498,-0.282601,-0.273716,0.577493,-0.822409,-0.315477,-0.741780,-1.657658,1.612398,-0.108136,-1.366012,-0.540990,-0.768648,0.044093,-0.119176,-1.608272,-0.816656,1.671253,-0.315477,0.761648,-0.915472,0.436114,-0.833884,0.781570,-0.745242,-0.738944,-0.982734,-0.738944,-0.714995,-0.757451,0.738944,0.738944,0.738944,0.738944,0.888055,-0.885909,-0.738944,0.407102,0.778770,-0.783690,-0.982014,0.736141,0.407102,-0.785327,-0.766244,-0.848226,-0.229280,0.675351,-0.619584,-0.238504,-0.761648,0.444195,0.830663,0.685811,-0.129505,-0.444195,0.771252,0.587436,0.797115,-0.253432,0.410598,-0.410598,0.636422,0.418891,0.465254,0.149380,-0.636422,0.681886,-0.477137,-0.939265,-0.827810,0.227782,-0.534603,-0.322210,-0.508533,0.334361,0.798989,-0.798989,-0.568095,-0.097666,-0.092667,-0.074039,0.568095,0.676589,0.276355,0.882281,0.833929,0.888831,-0.309375,1.409308,-0.078323,-0.138272,-0.183281,-0.697655,-0.649565,-0.197586,135.0
3,TRG002206,-1.536803,-1.099975,-0.826767,-0.655826,1.414214,1.198570,1.860978,-0.417799,0.934473,0.437887,1.273518,0.330031,-0.286897,0.354112,0.198721,0.785498,0.009849,0.703661,0.417418,0.193360,0.641270,-0.748127,0.155426,-0.429453,0.194057,0.820527,-0.540164,-0.015421,-0.962099,-1.123530,0.769419,-0.698587,-1.167155,0.121547,0.267493,0.388853,-0.806615,-1.150382,-0.186057,-1.323599,-0.015421,0.918768,-0.934835,0.470016,-0.904292,0.866173,-0.824690,-0.919033,-1.025371,-0.919033,-0.985606,-0.964938,0.919033,0.919033,0.919033,0.919033,0.813781,-1.016377,-0.919033,0.433661,0.919347,-0.966785,-1.024611,0.853320,0.433661,-0.967706,-0.873986,-1.052075,0.267965,0.824382,-1.128162,0.239304,-0.918768,0.488618,1.029624,0.797361,-0.097167,-0.488618,-0.272792,-0.228118,-0.274788,0.130630,0.860285,-0.860285,0.873770,0.925261,0.965562,0.511492,-0.873770,1.126312,-0.269805,-1.264815,-1.066791,0.658673,-1.115581,-1.074165,-0.942236,0.721776,0.856162,-0.856162,-0.596088,-0.092465,-0.085795,-0.072185,0.596088,1.034510,0.104683,0.706687,0.663496,0.713083,-0.151761,0.168875,-0.070674,-0.125894,-0.183281,-0.917409,-0.691620,-0.214034,12.0
4,TRG002210,0.840921,0.909112,-0.826767,-0.655826,-0.707107,-0.800726,-0.751612,-0.417799,-1.070122,-0.677748,1.273518,0.880483,1.183572,-0.263244,-0.665779,-0.611192,-0.548245,-0.590082,-0.669492,-0.333314,-0.526783,0.943305,-0.331273,-0.682848,-0.334348,0.170008,-1.002111,-0.338528,-0.528477,-1.013861,0.373760,-1.218972,-1.143366,-0.560838,-0.445669,0.359029,-1.294705,-1.061309,-0.847360,-1.189751,-0.338528,0.593697,-0.946119,0.396377,-0.733851,0.670209,-0.646068,-0.542092,-0.860282,-0.542092,-0.452418,-0.534920,0.542092,0.542092,0.542092,0.542092,0.762015,-0.758097,-0.542092,0.375380,0.619632,-0.592767,-0.859678,0.601616,0.375380,-0.596483,-0.638939,-1.205472,-0.246127,1.216525,-0.411005,-0.303305,-0.593697,0.395867,1.023552,0.791561,-0.095276,-0.395867,0.790007,0.499117,0.852575,-0.337811,-0.115270,0.115270,0.309556,0.623182,0.664921,0.301841,-0.309556,0.455904,-0.504823,-0.666583,-0.956489,0.344312,-0.162562,-0.539216,-0.024014,0.104828,0.740434,-0.740434,-0.539208,-0.097927,-0.093011,-0.074132,0.539208,0.130663,-0.171733,0.434892,0.399691,0.441051,0.114003,1.313876,-0.078713,-0.132826,-0.183281,-0.483605,-0.583366,-0.204678,109.0

In [10]:
output_path = "TrainDataset2025_Preprocessed_Iter.csv"

df_clean_iter.to_csv(output_path, index=False)
print("Saved:", output_path)

Saved: TrainDataset2025_Preprocessed_Iter.csv