In [60]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import random
import seaborn as sns
import scipy
import sklearn
from sklearn.svm import SVC
from scipy.stats import pearsonr
from sklearn import datasets, linear_model
from sklearn import preprocessing
from sklearn.pipeline import make_pipeline
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, accuracy_score, classification_report, confusion_matrix
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor, plot_tree, DecisionTreeClassifier
from sklearn.neural_network import MLPRegressor, MLPClassifier
from sklearn.preprocessing import OrdinalEncoder
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

#!pip install xlrd 
#!pip install category_encoders
import category_encoders as ce

In [61]:
df = pd.read_excel("TrainDataset2025.xls")
df.head()

,ID,pCR (outcome),RelapseFreeSurvival (outcome),Age,ER,PgR,HER2,TrippleNegative,ChemoGrade,Proliferation,HistologyType,LNStatus,TumourStage,Gene,original_shape_Elongation,original_shape_Flatness,original_shape_LeastAxisLength,original_shape_MajorAxisLength,original_shape_Maximum2DDiameterColumn,original_shape_Maximum2DDiameterRow,original_shape_Maximum2DDiameterSlice,original_shape_Maximum3DDiameter,original_shape_MeshVolume,original_shape_MinorAxisLength,original_shape_Sphericity,original_shape_SurfaceArea,original_shape_SurfaceVolumeRatio,original_shape_VoxelVolume,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,original_firstorder_Minimum,original_firstorder_Range,original_firstorder_RobustMeanAbsoluteDeviation,original_firstorder_RootMeanSquared,original_firstorder_Skewness,original_firstorder_TotalEnergy,original_firstorder_Uniformity,original_firstorder_Variance,original_glcm_Autocorrelation,original_glcm_ClusterProminence,original_glcm_ClusterShade,original_glcm_ClusterTendency,original_glcm_Contrast,original_glcm_Correlation,original_glcm_DifferenceAverage,original_glcm_DifferenceEntropy,original_glcm_DifferenceVariance,original_glcm_Id,original_glcm_Idm,original_glcm_Idmn,original_glcm_Idn,original_glcm_Imc1,original_glcm_Imc2,original_glcm_InverseVariance,original_glcm_JointAverage,original_glcm_JointEnergy,original_glcm_JointEntropy,original_glcm_MCC,original_glcm_MaximumProbability,original_glcm_SumAverage,original_glcm_SumEntropy,original_glcm_SumSquares,original_gldm_DependenceEntropy,original_gldm_DependenceNonUniformity,original_gldm_DependenceNonUniformityNormalized,original_gldm_DependenceVariance,original_gldm_GrayLevelNonUniformity,original_gldm_GrayLevelVariance,original_gldm_HighGrayLevelEmphasis,original_gldm_LargeDependenceEmphasis,original_gldm_LargeDependenceHighGrayLevelEmphasis,original_gldm_LargeDependenceLowGrayLevelEmphasis,original_gldm_LowGrayLevelEmphasis,original_gldm_SmallDependenceEmphasis,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,original_glrlm_GrayLevelNonUniformity,original_glrlm_GrayLevelNonUniformityNormalized,original_glrlm_GrayLevelVariance,original_glrlm_HighGrayLevelRunEmphasis,original_glrlm_LongRunEmphasis,original_glrlm_LongRunHighGrayLevelEmphasis,original_glrlm_LongRunLowGrayLevelEmphasis,original_glrlm_LowGrayLevelRunEmphasis,original_glrlm_RunEntropy,original_glrlm_RunLengthNonUniformity,original_glrlm_RunLengthNonUniformityNormalized,original_glrlm_RunPercentage,original_glrlm_RunVariance,original_glrlm_ShortRunEmphasis,original_glrlm_ShortRunHighGrayLevelEmphasis,original_glrlm_ShortRunLowGrayLevelEmphasis,original_glszm_GrayLevelNonUniformity,original_glszm_GrayLevelNonUniformityNormalized,original_glszm_GrayLevelVariance,original_glszm_HighGrayLevelZoneEmphasis,original_glszm_LargeAreaEmphasis,original_glszm_LargeAreaHighGrayLevelEmphasis,original_glszm_LargeAreaLowGrayLevelEmphasis,original_glszm_LowGrayLevelZoneEmphasis,original_glszm_SizeZoneNonUniformity,original_glszm_SizeZoneNonUniformityNormalized,original_glszm_SmallAreaEmphasis,original_glszm_SmallAreaHighGrayLevelEmphasis,original_glszm_SmallAreaLowGrayLevelEmphasis,original_glszm_ZoneEntropy,original_glszm_ZonePercentage,original_glszm_ZoneVariance,original_ngtdm_Busyness,original_ngtdm_Coarseness,original_ngtdm_Complexity,original_ngtdm_Contrast,original_ngtdm_Strength
0,TRG002174,1,144.0,41.0,0,0,0,1,3,3,1,1,2,1,0.813912,0.724080,23.781937,32.844370,37.696154,38.626416,34.713110,39.572718,14209.458330,26.732440,0.771675,3676.500012,0.258736,14263,-0.163500,0.708860,2897.68930,0.738088,0.406537,4.594629,2.114799,0.278008,0.248168,0.217628,-1.251833,3.366632,0.174026,0.450734,0.386237,2897.68930,0.670258,0.141574,3.328814,0.725849,-0.425324,0.438760,0.184265,0.407895,0.184265,0.685680,0.149585,0.907867,0.907867,0.963147,0.938578,-0.149786,0.425720,0.184265,1.806982,0.538903,1.309203,0.407895,0.714849,3.613964,1.124938,0.155756,4.529461,1164.363949,0.081635,38.233794,9559.892659,0.164871,3.375307,456.983173,1714.810208,142.526414,0.406173,0.005563,0.011679,0.004033,1805.333660,0.503341,0.248329,2.619511,36.191087,137.835476,10.779989,0.595122,3.865811,677.118614,0.184874,0.251409,19.138811,0.409396,0.789987,0.314248,27.545455,0.834711,0.082645,1.272727,4067578.818,1.565522e+07,1.170667e+06,0.931818,5.969697,0.180900,0.403535,0.517172,0.375126,3.325332,0.002314,3880771.500,473.464852,0.000768,0.182615,0.030508,0.000758
1,TRG002178,0,142.0,39.0,1,1,0,0,3,3,1,1,2,0,0.666118,0.476173,20.715461,43.504095,51.971146,41.761226,36.400549,53.310412,14202.708330,28.978871,0.603481,4699.678466,0.330900,14254,0.665558,2.322627,41105.32510,0.179893,0.730463,3.884960,3.857952,0.499454,1.562901,1.632745,-1.106491,4.964442,0.318599,1.698168,-0.634246,41105.32510,0.947174,0.441115,3.934749,0.070286,-0.048574,0.039166,0.027998,0.157776,0.027998,0.183795,0.027197,0.986001,0.986001,0.994400,0.990667,-0.070082,0.105206,0.027998,1.982916,0.939221,0.240095,0.157776,0.968917,3.965832,0.212098,0.016791,2.799725,4650.251438,0.326242,29.160771,13501.014310,0.026413,3.918549,585.940648,2342.457065,146.811544,0.270363,0.006518,0.012337,0.005064,1302.579572,0.694474,0.152763,3.433408,109.743182,438.113168,27.650685,0.391648,4.255471,159.837285,0.084497,0.130916,44.699577,0.241148,0.442279,0.190865,78.025000,0.975313,0.012344,1.037500,2403756.075,9.614769e+06,6.010027e+05,0.990625,15.850000,0.198125,0.444391,0.444391,0.444391,3.032144,0.005612,2372009.744,59.459710,0.004383,0.032012,0.001006,0.003685
2,TRG002204,1,135.0,31.0,0,0,0,1,2,1,1,0,2,1,0.645083,0.594470,21.659822,36.435505,32.984845,40.447497,42.379240,44.384682,10858.375000,23.503921,0.608183,3899.055524,0.359083,10960,0.638035,1.961740,19774.94893,0.136183,0.509910,4.760064,3.841710,0.400199,1.219685,1.153095,-1.025610,4.867321,0.231278,1.343236,0.545105,19774.94893,0.962589,0.316651,3.955045,0.043376,-0.031359,0.026057,0.020003,0.131035,0.020003,0.141291,0.019599,0.989998,0.989998,0.995999,0.993332,-0.048997,0.086544,0.020003,1.988349,0.957372,0.178540,0.131035,0.978347,3.976698,0.158537,0.011515,2.863091,3374.309307,0.307875,27.615779,10549.970990,0.018706,3.942792,584.343248,2336.739325,146.244229,0.264302,0.007181,0.013216,0.005672,1102.109263,0.764847,0.117576,3.590626,100.817995,402.737100,25.338218,0.352343,4.232295,114.255050,0.079355,0.130959,38.588656,0.222151,0.503046,0.151927,72.027027,0.973338,0.013331,1.040541,1561963.432,6.247801e+06,3.905040e+05,0.989865,20.405405,0.275749,0.534549,0.534549,0.534549,2.485848,0.006752,1540027.421,33.935384,0.007584,0.024062,0.000529,0.006447
3,TRG002206,0,12.0,35.0,0,0,0,1,3,3,1,1,3,1,0.770842,0.501228,26.590504,53.050724,66.910388,44.944410,66.760767,69.000000,26748.208330,40.893735,0.474509,9115.275207,0.340781,26899,0.759496,2.164869,72854.17151,0.087137,0.740609,3.421056,3.030400,0.442713,1.549668,1.660720,-0.851106,3.881506,0.309734,1.645732,-0.792678,72854.17151,0.978307,0.306963,3.973627,0.025128,-0.018371,0.015236,0.011845,0.122613,0.011845,0.092635,0.011702,0.994078,0.994078,0.997631,0.996052,-0.056651,0.065831,0.011845,1.993183,0.974758,0.114284,0.122613,0.987261,3.986367,0.102439,0.006770,2.756432,8662.085096,0.322023,22.976388,26315.470500,0.010847,3.967099,594.497230,2377.642849,148.710826,0.258225,0.004902,0.010811,0.003424,2701.187578,0.841781,0.079110,3.739820,125.498739,501.648278,31.461354,0.315045,4.412648,212.625994,0.065202,0.118981,48.370607,0.161327,0.399896,0.101685,99.019802,0.980394,0.009803,1.029703,7007670.723,2.803063e+07,1.751932e+06,0.992574,25.554455,0.253014,0.506185,0.506185,0.506185,2.606255,0.003755,6936740.794,46.859265,0.005424,0.013707,0.000178,0.004543
4,TRG002210,0,109.0,61.0,1,0,0,0,2,1,1,0,2,1,0.861035,0.750267,20.456571,27.265716,33.241540,30.594117,31.384710,35.042831,8846.541667,23.476732,0.756228,2735.354881,0.309200,8894,0.434385,1.832410,15697.30914,0.183666,0.787978,3.107181,2.315364,0.447799,1.209800,1.311328,-0.866201,3.181566,0.324996,1.328508,-0.732889,15697.30914,0.945787,0.301317,3.933264,0.069301,-0.048455,0.039564,0.028921,0.155224,0.028921,0.188503,0.028068,0.985540,0.985540,0.994216,0.990360,-0.061986,0.106835,0.028921,1.982575,0.937690,0.245543,0.155224,0.968114,3.965150,0.216623,0.017121,2.676170,3195.159883,0.359249,29.518487,8411.830447,0.027106,3.916348,594.187317,2375.516078,148.855127,0.270913,0.007222,0.012956,0.005788,750.787780,0.674880,0.162560,3.385162,110.775276,442.211336,27.916261,0.403709,4.140589,101.119011,0.091210,0.124509,41.234090,0.261101,0.473278,0.208056,56.034483,0.966112,0.016944,1.051724,1288913.690,5.155465e+06,3.222760e+05,0.987069,12.551724,0.216409,0.462282,0.462282,0.462282,2.809279,0.006521,1265399.054,39.621023,0.006585,0.034148,0.001083,0.005626

In [62]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Columns: 121 entries, ID to original_ngtdm_Strength
dtypes: float64(108), int64(12), object(1)
memory usage: 378.3+ KB

,pCR (outcome),RelapseFreeSurvival (outcome),Age,ER,PgR,HER2,TrippleNegative,ChemoGrade,Proliferation,HistologyType,LNStatus,TumourStage,Gene,original_shape_Elongation,original_shape_Flatness,original_shape_LeastAxisLength,original_shape_MajorAxisLength,original_shape_Maximum2DDiameterColumn,original_shape_Maximum2DDiameterRow,original_shape_Maximum2DDiameterSlice,original_shape_Maximum3DDiameter,original_shape_MeshVolume,original_shape_MinorAxisLength,original_shape_Sphericity,original_shape_SurfaceArea,original_shape_SurfaceVolumeRatio,original_shape_VoxelVolume,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,original_firstorder_Minimum,original_firstorder_Range,original_firstorder_RobustMeanAbsoluteDeviation,original_firstorder_RootMeanSquared,original_firstorder_Skewness,original_firstorder_TotalEnergy,original_firstorder_Uniformity,original_firstorder_Variance,original_glcm_Autocorrelation,original_glcm_ClusterProminence,original_glcm_ClusterShade,original_glcm_ClusterTendency,original_glcm_Contrast,original_glcm_Correlation,original_glcm_DifferenceAverage,original_glcm_DifferenceEntropy,original_glcm_DifferenceVariance,original_glcm_Id,original_glcm_Idm,original_glcm_Idmn,original_glcm_Idn,original_glcm_Imc1,original_glcm_Imc2,original_glcm_InverseVariance,original_glcm_JointAverage,original_glcm_JointEnergy,original_glcm_JointEntropy,original_glcm_MCC,original_glcm_MaximumProbability,original_glcm_SumAverage,original_glcm_SumEntropy,original_glcm_SumSquares,original_gldm_DependenceEntropy,original_gldm_DependenceNonUniformity,original_gldm_DependenceNonUniformityNormalized,original_gldm_DependenceVariance,original_gldm_GrayLevelNonUniformity,original_gldm_GrayLevelVariance,original_gldm_HighGrayLevelEmphasis,original_gldm_LargeDependenceEmphasis,original_gldm_LargeDependenceHighGrayLevelEmphasis,original_gldm_LargeDependenceLowGrayLevelEmphasis,original_gldm_LowGrayLevelEmphasis,original_gldm_SmallDependenceEmphasis,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,original_glrlm_GrayLevelNonUniformity,original_glrlm_GrayLevelNonUniformityNormalized,original_glrlm_GrayLevelVariance,original_glrlm_HighGrayLevelRunEmphasis,original_glrlm_LongRunEmphasis,original_glrlm_LongRunHighGrayLevelEmphasis,original_glrlm_LongRunLowGrayLevelEmphasis,original_glrlm_LowGrayLevelRunEmphasis,original_glrlm_RunEntropy,original_glrlm_RunLengthNonUniformity,original_glrlm_RunLengthNonUniformityNormalized,original_glrlm_RunPercentage,original_glrlm_RunVariance,original_glrlm_ShortRunEmphasis,original_glrlm_ShortRunHighGrayLevelEmphasis,original_glrlm_ShortRunLowGrayLevelEmphasis,original_glszm_GrayLevelNonUniformity,original_glszm_GrayLevelNonUniformityNormalized,original_glszm_GrayLevelVariance,original_glszm_HighGrayLevelZoneEmphasis,original_glszm_LargeAreaEmphasis,original_glszm_LargeAreaHighGrayLevelEmphasis,original_glszm_LargeAreaLowGrayLevelEmphasis,original_glszm_LowGrayLevelZoneEmphasis,original_glszm_SizeZoneNonUniformity,original_glszm_SizeZoneNonUniformityNormalized,original_glszm_SmallAreaEmphasis,original_glszm_SmallAreaHighGrayLevelEmphasis,original_glszm_SmallAreaLowGrayLevelEmphasis,original_glszm_ZoneEntropy,original_glszm_ZonePercentage,original_glszm_ZoneVariance,original_ngtdm_Busyness,original_ngtdm_Coarseness,original_ngtdm_Complexity,original_ngtdm_Contrast,original_ngtdm_Strength
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.00000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,4.000000e+02,4.000000e+02,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,4.000000e+02,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,4.000000e+02,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,4.000000e+02,400.000000,400.000000,400.000000,4.000000e+02,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,4.000000e+02,4.000000e+02,4.000000e+02,400.000000,400.000000,400.000000,4.000000e+02,4.000000e+02,4.000000e+02,4.000000e+02,400.000000,4.000000e+02,400.000000,400.000000,400.000000,400.000000,400.000000
mean,12.697500,56.000208,51.804674,0.547500,2.902500,2.797500,2.830000,9.875000,6.562500,8.63250,3.030000,2.607500,220.077500,0.716766,0.549817,23.072117,47.123568,47.975044,44.691151,47.519888,55.959049,20175.896562,31.331673,0.599114,7077.862397,0.394303,20286.662500,0.349420,2.553621,7.558204e+04,3.013113e-01,1.225883,2.810679,3.990295,0.692241,1.489130,1.529670,-1.047928,5.038224,0.506843,1.734983,-0.201434,7.558204e+04,0.886395,0.774701,3.715999,0.259496,-0.151342,0.127558,0.053479,0.325161,0.053479,2.698481e-01,0.048426,0.973261,0.973261,0.989304,0.982174,-0.140517,0.227191,0.053479,1.914246,0.861056,4.535711e-01,0.325201,0.922351,3.828492,4.000923e-01,0.045259,3.306906,5812.507878,0.243763,33.267788,18419.534984,0.056803,3.699739,541.950347,2085.262204,156.122383,0.325065,0.005497,0.011484,0.004000,2157.297056,0.694601,0.152700,3.190580,80.401079,310.756281,22.812278,0.452355,3.955578,340.638141,0.120189,0.172449,33.417605,0.278120,0.547245,0.210838,48.730722,0.874733,0.062633,1.260478,1.038107e+08,3.000160e+08,5.475941e+07,0.934880,10.672010,0.239151,3.920331e-01,3.957637e-01,3.911005e-01,2.722189e+00,0.003347,5.679717e+07,178.311246,32500.032620,0.056935,0.005965,0.029322
std,111.107417,27.137584,10.948522,0.498362,49.932114,49.937068,49.935558,86.092911,70.444284,86.20034,49.925801,0.897473,414.192346,0.164057,0.169573,9.948258,29.863864,24.136364,25.745205,27.378215,31.281043,34032.604046,14.929817,0.166765,13124.982232,0.124785,34116.955026,0.500398,0.720593,1.771190e+05,2.228900e-01,0.432459,0.794289,1.375773,0.214059,0.498683,0.490532,0.506797,1.435835,0.171557,0.480297,0.447253,1.771190e+05,0.100164,0.500969,0.548813,0.259498,0.153708,0.136369,0.045359,0.197784,0.045359,1.800264e-01,0.038106,0.022679,0.022679,0.009072,0.015120,0.103186,0.158959,0.045359,0.182253,0.123831,3.513830e-01,0.197970,0.076163,0.364506,3.079711e-01,0.044094,0.523883,10647.454674,0.095050,9.133694,33036.794878,0.050082,0.547861,51.098921,367.144828,76.371655,0.136965,0.002186,0.002953,0.002099,4168.813124,0.171297,0.085648,0.629373,48.801495,197.947990,16.930694,0.157343,0.406319,475.055615,0.043528,0.050184,22.730155,0.104823,0.137347,0.115990,69.761309,0.123567,0.061783,0.387635,1.048229e+09,3.174131e+09,7.352483e+08,0.096909,14.404000,0.132594,1.617334e-01,1.666319e-01,1.615922e-01,7.648849e-01,0.002419,7.063846e+08,1045.453432,177545.921568,0.047179,0.008379,0.115915
min,0.000000,0.000000,23.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.00000,0.000000,1.000000,0.000000,0.139299,0.099076,5.488466,12.466885,12.165525,13.038405,12.369317,15.524175,522.541667,9.197979,0.144064,438.477231,0.137183,539.000000,-1.717478,0.550056,9.187304e+02,-3.200000e-16,0.176432,1.703169,1.789861,0.278008,-0.495257,-0.782357,-3.489104,2.609159,0.174026,0.450734,-1.549694,9.187304e+02,0.560138,0.137128,1.000000,0.000000,-0.698575,0.000000,0.000000,-0.001169,0.000000,-3.200000e-16,0.000000,0.851249,0.851249,0.940500,0.900833,-0.704224,0.000000,0.000000,1.000000,0.318974,-3.200000e-16,0.000011,0.462222,2.000000,-3.200000e-16,0.000000,1.746059,26.291280,0.048778,15.274312,389.055659,0.000000,1.000000,271.103940,483.218378,90.322356,0.250008,0.001935,0.001969,0.000496,114.422115,0.500911,0.000000,1.000000,8.805742,17.663852,4.270105,0.250082,2.891378,28.080182,0.039053,0.067764,2.772991,0.065387,0.065387,0.018789,1.000000,0.500000,0.000000,1.000000,5.717762e+04,2.280370e+05,1.446278e+04,0.400000,1.000000,0.066991,7.050000e-11,7.050000e-11,7.050000e-11,-3.200000e-16,0.000008,0.000000e+00,0.000000,0.000248,0.000000,0.000000,0.000000
25%,0.000000,38.000000,44.516769,0.000000,0.000000,0.000000,0.000000,2.000000,1.000000,1.00000,0.000000,2.000000,0.000000,0.614122,0.419926,16.262250,28.392261,31.144823,29.017098,30.083218,34.874576,5505.239584,20.903237,0.470205,2231.665958,0.308054,5569.250000,0.017428,2.074745,1.447680e+04,1.137992e-01,0.912450,2.331916,3.085950,0.534436,1.160005,1.213290,-1.350085,4.039714,0.380808,1.413895,-0.506042,1.447680e+04,0.826570,0.444353,3.719606,0.049899,-0.238660,0.025996,0.017185,0.201195,0.017185,1.250156e-01,0.016882,0.960104,0.960104,0.984041,0.973402,-0.170635,0.109379,0.017185,1.921287,0.792010,1.649499e-01,0.201212,0.887377,3.842575,1.470214e-01,0.010937,2.936179,1139.215458,0.172886,25.742684,4884.762486,0.015007,3.677587,513.414113,2007.247351,134.087546,0.264226,0.003773,0.009998,0.002418,671.804105,0.535692,0.079064,2.822364,47.025407,176.723255,12.721094,0.335310,3.704837,115.002731,0.085970,0.135429,18.058657,0.189805,0.477469,0.104734,9.181818,0.834711,0.018428,1.056342,1.311764e+06,5.031858e+06,3.567324e+05,0.931818,2.087413,0.160370,3.199015e-01,3.199017e-01,3.184398e-01,2.340783e+00,0.001389,1.030473e+06,18.760570,0.001826,0.018628,0.000310,0.001464
50%,0.000000,55.000000,51.019507,1.000000,0.000000,0.000000,0.000000,2.000000,1.000000,1.00000,1.000000,2.000000,1.000000,0.744712,0.550761,21.600941,39.244226,41.115528,38.373141,39.427143,47.644499,11989.520835,27.704988,0.611201,4007.332154,0.370412,12080.000000,0.321150,2.433500,3.361665e+04,2.736016e-01,1.167068,2.638978,3.738263,0.667524,1.404673,1.457954,-1.104206,4.763696,0.488671,1.641282,-0.205314,3.361665e+04,0.910380,0.660989,3.861755,0.174519,-0.110508,0.085468,0.044440,0.290378,0.044440,2.614990e-01,0.042419,0.977780,0.977780,0.991112,0.985187,-0.122807,0.203644,0.044440,1.962628,0.890470,4.025256e-01,0.291124,0.942980,3.925257,3.563955e-01,0.032970,3.300025,2733.962122,0.237305,32.911012,10513.130930,0.044810,3.841732,545.821152,2157.785843,142.045819,0.289567,0.005473,0.011393,0.003985,1208.131646,0.645412,0.177294,3.249865,66.868684,260.943909,18.143410,0.437534,3.949369,207.088943,0.113047,0.167160,27.838675,0.273416,0.555676,0.208185,24.076923,0.916824,0.041588,1.130435,3.760290e+06,1.446362e+07,9.685342e+05,0.967391,5.170909,0.208256,4.073021e-01,4.095627e-01,4.054695e-01,2.814884e+00,0.002944,3.277334e+06,67.929659,0.004383,0.047740,0.002330,0.003276
75%,0.000000,73.000000,60.000000,1.000000,1.000000,1.000000,1.000000,3.000000,2.000000,1.00000,1.000000,3.000000,1.000000,0.840051,0.688378,27.723218,58.117748,59.407491,54.426544,58.753127,69.160947,23289.718750,38.054546,0.736629,7631.329455,0.459572,23473.500000,0.631555,2.852893,7.541352e+04,4.559082e-01,1.494012,3.035065,4.465178,0.819270,1.726168,1.764246,-0.770777,5.535964,0.611346,1.966944,0.039787,7.541352e+04,0.969985,0.982922,3.949659,0.402064,-0.032731,0.178206,0.079793,0.391504,0.079793,4.001249e-01,0.073295,0.991407,0.991407,0.996563,0.994272,-0.075312,0.320900,0.079793,1.986543,0.961267,6.799232e-01,0.391504,0.980355,3.973086,5.974409e-01,0.066728,3.641061,6814.045363,0.312826,40.010517,20866.900640,0.086715,3.943094,578.142544,2296.464498,149.927289,0.330603,0.006835,0.013148,0.005240,2288.530082,0.841872,0.232154,3.658762,103.354029,402.953448,28.606576,0.544409,4.227176,407.634309,0.147702,0.199018,43.591408,0.369707,0.627946,0.312460,61.054579,0.963144,0.082645,1.272727,1.012511e+07,3.861245e+07,2.688915e+06,0.985915,12.702912,0.277568,4.956921e-01,5.000049e-01,4.956920e-01,3.304411e+00,0.004798,9.079686e+06,157.370294,0.013769,0.085321,0.007962,0.009479
max,999.000000,144.000000,79.603012,1.000000,999.000000,999.000000,999.000000,999.000000,999.000000,999.00000,999.000000,4.000000,999.000000,0.985424,0.872753,92.516207,326.866827,155.756220,241.530536,237.033753,242.614921,528765.458300,126.141700,0.888133,219501.845200,0.839124,529659.000000,2.118644,5.940469,2.928334e+06,9.114111e-01,3.078672,9.176538,11.180875,1.664640,3.414142,3.395508,0.969298,12.240681,1.253614,3.786760,2.515312,2.928334e+06,1.000000,3.959871,3.999955,1.209880,0.633704,0.767273,0.297502,1.000000,0.297502,8.669089e-01,0.205763,1.000000,1.000000,1.000000,1.000000,0.000000,0.793518,0.297502,1.999989,1.000000,1.815373e+00,1.000000,1.000000,3.999978,1.517871e+00,0.237631,4.929221,137989.523900,0.602150,58.513781,528500.270300,0.219931,3.999970,655.755882,2617.871609,608.902614,1.000000,0.016475,0.023252,0.014780,71002.622480,1.000000,0.249544,3.999673,461.989676,1845.719103,149.377763,1.000000,5.651427,6957.420630,0.262586,0.423848,227.216258,0.498117,1.025800,0.457650,594.003356,1.000000,0.250000,3.400000,1.467713e+10,5.870849e+10,1.419410e+10,1.000000,117.476510,1.000000,8.571429e-01,8.773779e-01,8.571429e-01,4.947427e+00,0.011301,1.390001e+10,20764.693790,1000000.000000,0.285100,0.060742,1.145601

In [65]:
df.replace(999, pd.NA, inplace=True)

In [66]:
missing_cols = df.isna().sum()
missing_cols = missing_cols[missing_cols > 0]
missing_cols

pCR (outcome)       5
PgR                 1
HER2                1
TrippleNegative     1
ChemoGrade          3
Proliferation       2
HistologyType       3
LNStatus            1
Gene               88
dtype: int64

In [67]:
missing_cols.dtypes
df.dtypes

ID                                                     object
pCR (outcome)                                          object
RelapseFreeSurvival (outcome)                         float64
Age                                                   float64
ER                                                      int64
PgR                                                    object
HER2                                                   object
TrippleNegative                                        object
ChemoGrade                                             object
Proliferation                                          object
HistologyType                                          object
LNStatus                                               object
TumourStage                                             int64
Gene                                                   object
original_shape_Elongation                             float64
original_shape_Flatness                               float64
original_shape_LeastAxisLength                        float64
original_shape_MajorAxisLength                        float64
original_shape_Maximum2DDiameterColumn                float64
original_shape_Maximum2DDiameterRow                   float64
original_shape_Maximum2DDiameterSlice                 float64
original_shape_Maximum3DDiameter                      float64
original_shape_MeshVolume                             float64
original_shape_MinorAxisLength                        float64
original_shape_Sphericity                             float64
original_shape_SurfaceArea                            float64
original_shape_SurfaceVolumeRatio                     float64
original_shape_VoxelVolume                              int64
original_firstorder_10Percentile                      float64
original_firstorder_90Percentile                      float64
original_firstorder_Energy                            float64
original_firstorder_Entropy                           float64
original_firstorder_InterquartileRange                float64
original_firstorder_Kurtosis                          float64
original_firstorder_Maximum                           float64
original_firstorder_MeanAbsoluteDeviation             float64
original_firstorder_Mean                              float64
original_firstorder_Median                            float64
original_firstorder_Minimum                           float64
original_firstorder_Range                             float64
original_firstorder_RobustMeanAbsoluteDeviation       float64
original_firstorder_RootMeanSquared                   float64
original_firstorder_Skewness                          float64
original_firstorder_TotalEnergy                       float64
original_firstorder_Uniformity                        float64
original_firstorder_Variance                          float64
original_glcm_Autocorrelation                         float64
original_glcm_ClusterProminence                       float64
original_glcm_ClusterShade                            float64
original_glcm_ClusterTendency                         float64
original_glcm_Contrast                                float64
original_glcm_Correlation                             float64
original_glcm_DifferenceAverage                       float64
original_glcm_DifferenceEntropy                       float64
original_glcm_DifferenceVariance                      float64
original_glcm_Id                                      float64
original_glcm_Idm                                     float64
original_glcm_Idmn                                    float64
original_glcm_Idn                                     float64
original_glcm_Imc1                                    float64
original_glcm_Imc2                                    float64
original_glcm_InverseVariance                         float64
original_glcm_JointAverage                            float64
original_glcm_JointEnergy                             float64
original_glcm_JointEntropy                            float64
original_glcm_MCC                                     float64
original_glcm_MaximumProbability                      float64
original_glcm_SumAverage                              float64
original_glcm_SumEntropy                              float64
original_glcm_SumSquares                              float64
original_gldm_DependenceEntropy                       float64
original_gldm_DependenceNonUniformity                 float64
original_gldm_DependenceNonUniformityNormalized       float64
original_gldm_DependenceVariance                      float64
original_gldm_GrayLevelNonUniformity                  float64
original_gldm_GrayLevelVariance                       float64
original_gldm_HighGrayLevelEmphasis                   float64
original_gldm_LargeDependenceEmphasis                 float64
original_gldm_LargeDependenceHighGrayLevelEmphasis    float64
original_gldm_LargeDependenceLowGrayLevelEmphasis     float64
original_gldm_LowGrayLevelEmphasis                    float64
original_gldm_SmallDependenceEmphasis                 float64
original_gldm_SmallDependenceHighGrayLevelEmphasis    float64
original_gldm_SmallDependenceLowGrayLevelEmphasis     float64
original_glrlm_GrayLevelNonUniformity                 float64
original_glrlm_GrayLevelNonUniformityNormalized       float64
original_glrlm_GrayLevelVariance                      float64
original_glrlm_HighGrayLevelRunEmphasis               float64
original_glrlm_LongRunEmphasis                        float64
original_glrlm_LongRunHighGrayLevelEmphasis           float64
original_glrlm_LongRunLowGrayLevelEmphasis            float64
original_glrlm_LowGrayLevelRunEmphasis                float64
original_glrlm_RunEntropy                             float64
original_glrlm_RunLengthNonUniformity                 float64
original_glrlm_RunLengthNonUniformityNormalized       float64
original_glrlm_RunPercentage                          float64
original_glrlm_RunVariance                            float64
original_glrlm_ShortRunEmphasis                       float64
original_glrlm_ShortRunHighGrayLevelEmphasis          float64
original_glrlm_ShortRunLowGrayLevelEmphasis           float64
original_glszm_GrayLevelNonUniformity                 float64
original_glszm_GrayLevelNonUniformityNormalized       float64
original_glszm_GrayLevelVariance                      float64
original_glszm_HighGrayLevelZoneEmphasis              float64
original_glszm_LargeAreaEmphasis                      float64
original_glszm_LargeAreaHighGrayLevelEmphasis         float64
original_glszm_LargeAreaLowGrayLevelEmphasis          float64
original_glszm_LowGrayLevelZoneEmphasis               float64
original_glszm_SizeZoneNonUniformity                  float64
original_glszm_SizeZoneNonUniformityNormalized        float64
original_glszm_SmallAreaEmphasis                      float64
original_glszm_SmallAreaHighGrayLevelEmphasis         float64
original_glszm_SmallAreaLowGrayLevelEmphasis          float64
original_glszm_ZoneEntropy                            float64
original_glszm_ZonePercentage                         float64
original_glszm_ZoneVariance                           float64
original_ngtdm_Busyness                               float64
original_ngtdm_Coarseness                             float64
original_ngtdm_Complexity                             float64
original_ngtdm_Contrast                               float64
original_ngtdm_Strength                               float64
dtype: object

In [70]:
# Get columns with missing values
missing_cols = df.columns[df.isna().any()]

# Missing data summary
summary = pd.DataFrame({
    'Column': missing_cols,
    'MissingCount': [df[col].isna().sum() for col in missing_cols],
    'Dtype': [df[col].dtype for col in missing_cols]
})

print(summary)

            Column  MissingCount   Dtype
0    pCR (outcome)             5  object
1              PgR             1  object
2             HER2             1  object
3  TrippleNegative             1  object
4       ChemoGrade             3  object
5    Proliferation             2  object
6    HistologyType             3  object
7         LNStatus             1  object
8             Gene            88  object

In [71]:
df_dropped =  df.dropna(subset=['pCR (outcome)'])
df_dropped.shape

(395, 121)

In [72]:
missing_cols = df_dropped.columns[df_dropped.isna().any()]
# Missing data summary
summary = pd.DataFrame({
    'Column': missing_cols,
    'MissingCount': [df_dropped[col].isna().sum() for col in missing_cols],
    'Dtype': [df_dropped[col].dtype for col in missing_cols]
})

print(summary)

            Column  MissingCount   Dtype
0              PgR             1  object
1             HER2             1  object
2  TrippleNegative             1  object
3       ChemoGrade             3  object
4    Proliferation             2  object
5    HistologyType             3  object
6         LNStatus             1  object
7             Gene            85  object

In [73]:
'''
df_imputed = df_dropped.copy()

cat_columns = df_imputed.select_dtypes(include=['object', 'category']).columns

cat_cols_to_encode = cat_columns.drop('pCR (outcome)')
encoder = ce.OrdinalEncoder()
nan_placeholder = "__MISSING__"

# Fill NaNs with the placeholder string
df_imputed[cat_cols_to_encode] = df_imputed[cat_cols_to_encode].fillna(nan_placeholder)
df_imputed[cat_cols_to_encode] = encoder.fit_transform(df_imputed[cat_cols_to_encode])

df_imputed.head()
'''

'\ndf_imputed = df_dropped.copy()\n\ncat_columns = df_imputed.select_dtypes(include=[\'object\', \'category\']).columns\n\ncat_cols_to_encode = cat_columns.drop(\'pCR (outcome)\')\nencoder = ce.OrdinalEncoder()\nnan_placeholder = "__MISSING__"\n\n# Fill NaNs with the placeholder string\ndf_imputed[cat_cols_to_encode] = df_imputed[cat_cols_to_encode].fillna(nan_placeholder)\ndf_imputed[cat_cols_to_encode] = encoder.fit_transform(df_imputed[cat_cols_to_encode])\n\ndf_imputed.head()\n'

In [78]:

df_imputed = df_dropped.copy()

# Select categorical columns
cat_columns = df_imputed.select_dtypes(include=['object', 'category']).columns
cat_cols_to_encode = cat_columns.drop('pCR (outcome)')

encoder = ce.OrdinalEncoder(handle_missing='return_nan') 


# Encode categorical features
df_imputed[cat_cols_to_encode] = encoder.fit_transform(df_imputed[cat_cols_to_encode])


## Imputation with IterativeImputer
# Separate target
y_target = df_imputed['pCR (outcome)']
X_features = df_imputed.drop(columns=['pCR (outcome)'])

# Iterative Imputer
imputer = IterativeImputer(max_iter=20, random_state=42)
X_imputed = imputer.fit_transform(X_features)

# Convert back to DataFrame
X_imputed_df = pd.DataFrame(X_imputed,
                            columns=X_features.columns,
                            index=X_features.index)

# Round encoded categorical columns back to integers
for col in cat_cols_to_encode:
    max_val = df_imputed[col].max()
    min_val = df_imputed[col].min()
    X_imputed_df[col] = X_imputed_df[col].clip(lower=min_val, upper=max_val)
    X_imputed_df[col] = X_imputed_df[col].round().astype(int)

    
# Inverse transform encoded categorical columns
X_imputed_df[cat_cols_to_encode] = encoder.inverse_transform(X_imputed_df[cat_cols_to_encode])


# Recombine target
final_df = pd.concat([X_imputed_df, y_target], axis=1)

print("\n--- Missing Value Check ---")
print(final_df.isna().sum())

--- Missing Value Check ---
ID                                                    0
RelapseFreeSurvival (outcome)                         0
Age                                                   0
ER                                                    0
PgR                                                   0
HER2                                                  0
TrippleNegative                                       0
ChemoGrade                                            0
Proliferation                                         0
HistologyType                                         0
LNStatus                                              0
TumourStage                                           0
Gene                                                  0
original_shape_Elongation                             0
original_shape_Flatness                               0
original_shape_LeastAxisLength                        0
original_shape_MajorAxisLength                        0
original_shape_Maximum2DDiameterColumn                0
original_shape_Maximum2DDiameterRow                   0
original_shape_Maximum2DDiameterSlice                 0
original_shape_Maximum3DDiameter                      0
original_shape_MeshVolume                             0
original_shape_MinorAxisLength                        0
original_shape_Sphericity                             0
original_shape_SurfaceArea                            0
original_shape_SurfaceVolumeRatio                     0
original_shape_VoxelVolume                            0
original_firstorder_10Percentile                      0
original_firstorder_90Percentile                      0
original_firstorder_Energy                            0
original_firstorder_Entropy                           0
original_firstorder_InterquartileRange                0
original_firstorder_Kurtosis                          0
original_firstorder_Maximum                           0
original_firstorder_MeanAbsoluteDeviation             0
original_firstorder_Mean                              0
original_firstorder_Median                            0
original_firstorder_Minimum                           0
original_firstorder_Range                             0
original_firstorder_RobustMeanAbsoluteDeviation       0
original_firstorder_RootMeanSquared                   0
original_firstorder_Skewness                          0
original_firstorder_TotalEnergy                       0
original_firstorder_Uniformity                        0
original_firstorder_Variance                          0
original_glcm_Autocorrelation                         0
original_glcm_ClusterProminence                       0
original_glcm_ClusterShade                            0
original_glcm_ClusterTendency                         0
original_glcm_Contrast                                0
original_glcm_Correlation                             0
original_glcm_DifferenceAverage                       0
original_glcm_DifferenceEntropy                       0
original_glcm_DifferenceVariance                      0
original_glcm_Id                                      0
original_glcm_Idm                                     0
original_glcm_Idmn                                    0
original_glcm_Idn                                     0
original_glcm_Imc1                                    0
original_glcm_Imc2                                    0
original_glcm_InverseVariance                         0
original_glcm_JointAverage                            0
original_glcm_JointEnergy                             0
original_glcm_JointEntropy                            0
original_glcm_MCC                                     0
original_glcm_MaximumProbability                      0
original_glcm_SumAverage                              0
original_glcm_SumEntropy                              0
original_glcm_SumSquares                              0
original_gldm_DependenceEntropy                       0
original_gldm_DependenceNonUniformity                 0
original_gldm_DependenceNonUniformityNormalized       0
original_gldm_DependenceVariance                      0
original_gldm_GrayLevelNonUniformity                  0
original_gldm_GrayLevelVariance                       0
original_gldm_HighGrayLevelEmphasis                   0
original_gldm_LargeDependenceEmphasis                 0
original_gldm_LargeDependenceHighGrayLevelEmphasis    0
original_gldm_LargeDependenceLowGrayLevelEmphasis     0
original_gldm_LowGrayLevelEmphasis                    0
original_gldm_SmallDependenceEmphasis                 0
original_gldm_SmallDependenceHighGrayLevelEmphasis    0
original_gldm_SmallDependenceLowGrayLevelEmphasis     0
original_glrlm_GrayLevelNonUniformity                 0
original_glrlm_GrayLevelNonUniformityNormalized       0
original_glrlm_GrayLevelVariance                      0
original_glrlm_HighGrayLevelRunEmphasis               0
original_glrlm_LongRunEmphasis                        0
original_glrlm_LongRunHighGrayLevelEmphasis           0
original_glrlm_LongRunLowGrayLevelEmphasis            0
original_glrlm_LowGrayLevelRunEmphasis                0
original_glrlm_RunEntropy                             0
original_glrlm_RunLengthNonUniformity                 0
original_glrlm_RunLengthNonUniformityNormalized       0
original_glrlm_RunPercentage                          0
original_glrlm_RunVariance                            0
original_glrlm_ShortRunEmphasis                       0
original_glrlm_ShortRunHighGrayLevelEmphasis          0
original_glrlm_ShortRunLowGrayLevelEmphasis           0
original_glszm_GrayLevelNonUniformity                 0
original_glszm_GrayLevelNonUniformityNormalized       0
original_glszm_GrayLevelVariance                      0
original_glszm_HighGrayLevelZoneEmphasis              0
original_glszm_LargeAreaEmphasis                      0
original_glszm_LargeAreaHighGrayLevelEmphasis         0
original_glszm_LargeAreaLowGrayLevelEmphasis          0
original_glszm_LowGrayLevelZoneEmphasis               0
original_glszm_SizeZoneNonUniformity                  0
original_glszm_SizeZoneNonUniformityNormalized        0
original_glszm_SmallAreaEmphasis                      0
original_glszm_SmallAreaHighGrayLevelEmphasis         0
original_glszm_SmallAreaLowGrayLevelEmphasis          0
original_glszm_ZoneEntropy                            0
original_glszm_ZonePercentage                         0
original_glszm_ZoneVariance                           0
original_ngtdm_Busyness                               0
original_ngtdm_Coarseness                             0
original_ngtdm_Complexity                             0
original_ngtdm_Contrast                               0
original_ngtdm_Strength                               0
pCR (outcome)                                         0
dtype: int64

In [79]:
## Logistic Regression
X = final_df.drop(["pCR (outcome)", "ID"], axis=1)
y = final_df["pCR (outcome)"]
y = y.astype(int)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

# Pipeline = scaling + logistic regression
pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("clf", LogisticRegression(solver="lbfgs", max_iter=1000))
])

# K-fold CV
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = cross_val_score(pipe, X, y, cv=cv, scoring="accuracy")

print("Cross-validation scores:", cv_scores)
print("Mean CV accuracy: %.3f ± %.3f" % (cv_scores.mean(), cv_scores.std()))

# Fit on train and test
pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)

print("Test Accuracy: %.3f" % accuracy_score(y_test, y_pred))

Cross-validation scores: [0.78481013 0.84810127 0.79746835 0.75949367 0.74683544]
Mean CV accuracy: 0.787 ± 0.035
Test Accuracy: 0.815

[]

In [52]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
#print(X.isna().sum())
print(X['Gene'])

0      1.0
1      0.0
2      1.0
3      1.0
4      1.0
5      1.0
6      1.0
7      1.0
8      0.0
9      0.0
11     1.0
12     1.0
13     0.0
14     0.0
15     0.0
16     1.0
17     0.0
18     0.0
19     1.0
20     0.0
21     1.0
22     0.0
23     1.0
24     0.0
25     1.0
26     1.0
27     1.0
28     1.0
29     1.0
30     0.0
31     0.0
32     1.0
33     1.0
34     0.0
35     1.0
36     0.0
37     0.0
38     0.0
39     1.0
40     0.0
41     0.0
42     0.0
43     1.0
44     1.0
45     0.0
46     0.0
47     0.0
48     0.0
49     0.0
50     0.0
51     0.0
52     0.0
53     0.0
54     0.0
55     1.0
56     0.0
57     0.0
58     0.0
59     1.0
60     0.0
61     0.0
62     0.0
63     0.0
64     1.0
65     0.0
66     1.0
67     0.0
68     0.0
69     1.0
70     1.0
71     0.0
72     0.0
73     0.0
74     1.0
75     0.0
76     0.0
77     0.0
78     0.0
79     0.0
80     0.0
81     1.0
82     1.0
83     0.0
84     0.0
85     0.0
86     0.0
87     0.0
88     0.0
89     1.0
90     0.0
91     0.0
92     0.0
93     0.0
94     0.0
95     0.0
96     0.0
97     1.0
98     1.0
99     0.0
100    1.0
101    0.0
102    1.0
103    0.0
104    0.0
105    0.0
106    1.0
107    0.0
108    0.0
109    1.0
110    0.0
111    0.0
112    0.0
113    0.0
114    0.0
115    1.0
116    0.0
117    0.0
118    0.0
119    1.0
120    0.0
121    0.0
122    0.0
123    0.0
124    1.0
125    1.0
126    0.0
127    1.0
128    0.0
129    1.0
130    1.0
131    1.0
132    0.0
133    0.0
134    0.0
135    0.0
136    0.0
137    0.0
138    1.0
139    1.0
140    1.0
141    0.0
142    1.0
143    1.0
144    1.0
145    1.0
146    0.0
147    0.0
148    1.0
149    1.0
150    0.0
151    1.0
152    0.0
153    0.0
154    1.0
155    1.0
156    1.0
157    1.0
158    0.0
159    0.0
160    1.0
161    0.0
162    1.0
163    1.0
164    1.0
165    1.0
166    1.0
167    0.0
168    1.0
169    1.0
170    1.0
171    1.0
172    1.0
173    0.0
174    1.0
175    1.0
176    1.0
177    1.0
178    0.0
179    1.0
180    1.0
181    1.0
182    1.0
183    1.0
184    1.0
185    NaN
186    1.0
187    0.0
188    1.0
189    NaN
190    1.0
191    1.0
192    1.0
193    1.0
194    1.0
195    0.0
196    0.0
197    0.0
198    1.0
199    0.0
200    0.0
201    1.0
202    1.0
203    0.0
204    0.0
205    1.0
206    0.0
207    1.0
208    0.0
209    0.0
210    0.0
211    1.0
212    0.0
213    0.0
214    1.0
215    1.0
216    1.0
217    0.0
218    1.0
219    0.0
220    1.0
221    0.0
222    1.0
223    1.0
224    0.0
225    1.0
226    0.0
227    1.0
228    0.0
229    0.0
230    0.0
231    0.0
232    0.0
233    0.0
234    1.0
235    1.0
236    0.0
237    0.0
238    1.0
239    0.0
240    1.0
241    0.0
242    0.0
243    0.0
244    1.0
245    0.0
246    0.0
247    0.0
248    0.0
249    0.0
250    0.0
251    0.0
252    0.0
253    1.0
254    0.0
255    0.0
256    0.0
257    1.0
258    0.0
259    0.0
260    0.0
261    0.0
262    1.0
263    0.0
264    0.0
265    0.0
266    0.0
267    0.0
268    1.0
269    0.0
270    0.0
271    0.0
272    0.0
273    0.0
274    0.0
275    0.0
276    0.0
277    0.0
278    0.0
279    0.0
280    0.0
281    0.0
282    1.0
283    0.0
284    1.0
285    0.0
286    1.0
287    0.0
288    0.0
289    0.0
290    0.0
291    0.0
292    0.0
293    0.0
294    0.0
295    0.0
296    1.0
297    0.0
298    0.0
299    0.0
300    0.0
301    0.0
302    0.0
303    0.0
304    0.0
305    0.0
306    0.0
307    0.0
308    0.0
309    0.0
310    0.0
311    1.0
312    0.0
313    1.0
314    0.0
315    0.0
316    0.0
317    0.0
318    0.0
319    1.0
320    0.0
321    0.0
322    0.0
323    0.0
324    0.0
325    0.0
326    0.0
327    1.0
328    1.0
329    0.0
330    0.0
331    0.0
332    0.0
333    0.0
334    0.0
335    1.0
336    0.0
337    0.0
338    0.0
339    0.0
340    0.0
341    0.0
343    0.0
344    0.0
345    0.0
346    0.0
347    0.0
348    0.0
349    0.0
350    0.0
351    1.0
352    0.0
353    0.0
354    0.0
355    0.0
356    0.0
357    0.0
358    0.0
359    0.0
360    0.0
361    0.0
362    0.0
363    0.0
364    0.0
365    0.0
367    0.0
368    0.0
369    0.0
370    0.0
371    0.0
374    0.0
375    0.0
376    0.0
377    0.0
378    0.0
379    0.0
380    0.0
381    0.0
382    0.0
383    0.0
384    0.0
385    0.0
386    0.0
387    0.0
388    0.0
389    0.0
390    0.0
391    0.0
392    0.0
393    0.0
394    0.0
395    0.0
396    0.0
397    0.0
398    0.0
399    0.0
Name: Gene, dtype: object